Repository COSC310-Team12/ToDoList, pull requests merged in 2022-11, with the labels that each got.

#26 Added searchbar and made to-dos searchable
  app/src/main/java/com/example/todolist/MainActivity.java
  app/src/main/java/com/example/todolist/ToDoAdapter.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/todo_item.xml
Labels: enhancement

#41 Mulitple "Graded" filters bug fixed
  app/src/main/java/com/example/todolist/AddTagActivity.java
  app/src/main/java/com/example/todolist/EditToDo.java
  app/src/main/java/com/example/todolist/FilterPowerMenuItem.java
  app/src/main/java/com/example/todolist/GradeReceived.java
  app/src/main/java/com/example/todolist/MainActivity.java
  app/src/main/java/com/example/todolist/NotificationSender.java
  app/src/main/java/com/example/todolist/ToDo.java
  app/src/main/java/com/example/todolist/totalGrade.java
Labels: bug

#40 First task not adding bug fix
  app/src/main/java/com/example/todolist/AddTagActivity.java
  app/src/main/java/com/example/todolist/EditToDo.java
  app/src/main/java/com/example/todolist/FilterPowerMenuItem.java
  app/src/main/java/com/example/todolist/GradeReceived.java
  app/src/main/java/com/example/todolist/MainActivity.java
  app/src/main/java/com/example/todolist/NotificationSender.java
  app/src/main/java/com/example/todolist/ToDo.java
  app/src/main/java/com/example/todolist/totalGrade.java
Labels: bug

#30 Added to README.md
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/todolist/EditTagActivity.java
  app/src/main/java/com/example/todolist/EditToDoActivity.java
  app/src/main/java/com/example/todolist/MainActivity.java
  app/src/main/res/layout/activity_edit_tag.xml
  app/src/main/res/layout/activity_edit_todo.xml
  app/src/test/java/com/example/todolist/EditToDoActivityUnitTest.java
Labels: documentation

#44 Small improvements to README
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/todolist/EditTagActivity.java
  app/src/main/java/com/example/todolist/MainActivity.java
  app/src/main/java/com/example/todolist/TotalGradeActivity.java
  app/src/main/res/layout/activity_total_grade.xml
Labels: documentation
